project:
  type: website
  output-dir: docs

website:
  title: "Bren Calculus Workshop"
  sidebar:
    style: docked
    search: true
    contents: 
      - text: "Home"
        href: index.qmd
      - text: "Day 1: Algebra"
        href: algebra.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

