---
title: "Bren Calculus Workshop"
---

# Welcome incoming MESM!

Congratulations on your acceptance and decision to attend the Bren School of Environmental Science and Management. This website will host course content for the Calculus Workshop during Orientation week. Use the tabs to access lectures, problems sets, and links to useful resources.

## Instructor

Nathaniel Grimes (nggrimes@ucsb.edu)

Office: BH 3007

## Links

- [Download copy of Syllabus](syllabus.pdf)

- [**Follow this link for class pre-survey!**](https://docs.google.com/forms/d/13qlU8WEgVMUxiuF9gezNgu5oAbgDX4zeN1QcjbZssfM/edit)

## Objectives

Bren students come from all walks of life. Some incoming students might be twenty year career professionals in everything but math. Others might be right out of their math Bachelors degree armed with multivariate calculus and real analysis. This workshop is meant to get everyone to a sufficient level to excel in all the courses offered at Bren. Collaboration is essential during your MESM program. This workshop will build teams so that everyone can benefit from diverse backgrounds in both math and life. The primary workshop objectives are as follows:

-   Reinforce math skills used in Bren courses

-   Understand how math and calculus are used in Environmental Science

-   Help transition to graduate school life

-   Build collaborative environment

## Workshop Design

New research has shown that active learning outside of traditional lecture formats boosts student engagement, understanding, and comfort.

We'll be using a Team Based Learning (TBL) environment. Students will be grouped into teams of 4-5. [Please take this survey](https://docs.google.com/forms/d/13qlU8WEgVMUxiuF9gezNgu5oAbgDX4zeN1QcjbZssfM/edit) so I can balance teams across math comfort, background, and when the last time you did a problem set. Teams will work and collaborate together throughout the workshop.

## Schedule

Thursday September 19, 2024 **12:00 P.M. - 2:00 P.M.**: Introduction, Algebra and pre-calculus review, e.g. exponents and logarithms

Friday September 20, 2024 **9:00 A.M. - 11:00 A.M.**: Graphing, Limits, and Fundamentals of Calculus

Friday September 20, 2024 **12:00 P.M. - 2:00 P.M.**: Rules and Applications of derivatives

Monday September 23, 2024 **9:00 A.M. - 11:00 A.M.**: Integration

Tuesday September 24, 2024 **12:30 P.M. - 2:30 P.M.**: Differential Equations and Computational Calculus, i.e. let a computer do the work
